import os


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STIMULI_DIR = os.path.join(BASE_DIR, "stimuli")


DURATION=2.0
WAITING=0

SESSION_TYPE = "BEHAVIORAL"  # "BEHAVIORAL" or "SEEG"

# Neon Companion recording is started/stopped manually by the experimenter.
USE_NEON = True
NEON_DISCOVERY_TIMEOUT_S = 10.0
NEON_RETRY_INTERVAL_S = 1.0
NEON_SHUTDOWN_FLUSH_TIMEOUT_S = 5.0

# Positions use PsychoPy's ``height`` units. The bottom-left corner remains
# empty for the existing SEEG optical marker.
NEON_APRILTAG_SIZE = 0.10
NEON_APRILTAG_POSITIONS = (
    (-0.72, 0.44),
    (0.00, 0.44),
    (0.72, 0.44),
    (-0.83, 0.00),
    (0.83, 0.00),
    (0.00, -0.44),
    (0.72, -0.44),
)

SESSION_PROFILES = {
    "BEHAVIORAL": {
        "target_refresh_hz": 60,
        "use_labjack": False,
        "show_sync_marker": False,
    },
    "SEEG": {
        "target_refresh_hz": 144,
        "use_labjack": True,
        "show_sync_marker": True,
    },
}

if SESSION_TYPE not in SESSION_PROFILES:
    valid_types = ", ".join(SESSION_PROFILES)
    raise ValueError(
        f"Unknown SESSION_TYPE: {SESSION_TYPE}. Choose one of: {valid_types}"
    )

_SESSION_PROFILE = SESSION_PROFILES[SESSION_TYPE]
TARGET_REFRESH_HZ = _SESSION_PROFILE["target_refresh_hz"]
USE_LABJACK = _SESSION_PROFILE["use_labjack"]
SHOW_SYNC_MARKER = _SESSION_PROFILE["show_sync_marker"]
REFRESH_RATE_TOLERANCE_HZ = 1.0


def seconds_to_frames(duration_s):
    return int(round(duration_s * TARGET_REFRESH_HZ))


QUESTION_DURATION_S = 3.0
REVEAL_DURATION_S = 0.8
RESPONSE_TIMEOUT_S = 10.0
FEEDBACK_DURATION_S = 0.5
ISI_MIN_S = 0.75
ISI_MAX_S = 1.0
PRACTICE_FEEDBACK_DURATION_S = 0.5
PRACTICE_DONE_DURATION_S = 2.5
PRACTICE_PHASE_GAP_DURATION_S = 0.5

QUESTION_FRAMES = seconds_to_frames(QUESTION_DURATION_S)
REVEAL_FRAMES = seconds_to_frames(REVEAL_DURATION_S)
RESPONSE_TIMEOUT_FRAMES = seconds_to_frames(RESPONSE_TIMEOUT_S)
FEEDBACK_FRAMES = seconds_to_frames(FEEDBACK_DURATION_S)
PRACTICE_FEEDBACK_FRAMES = seconds_to_frames(PRACTICE_FEEDBACK_DURATION_S)
PRACTICE_DONE_FRAMES = seconds_to_frames(PRACTICE_DONE_DURATION_S)
PRACTICE_PHASE_GAP_FRAMES = seconds_to_frames(PRACTICE_PHASE_GAP_DURATION_S)

WIDTH = 1920
HEIGHT = 1080
_SYNC_MARKER_MULTIPLIER = int(SHOW_SYNC_MARKER)
FRAME_EXAMPLE_fa = 4 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_ga = 5 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_fr = 6 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_gr = 7 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_ha = 8 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_hr = 9 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_fcs = 10 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_fcf = 11 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_gcs = 12 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_gcf = 13 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_hcs = 14 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_hcf = 15 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_bq = 16 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_bp = 17 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_bl = 18 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_br = 19 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_bss = 20 * _SYNC_MARKER_MULTIPLIER
FRAME_EXAMPLE_bf = 21 * _SYNC_MARKER_MULTIPLIER
MODE=0
#0전부/1food빼고/2유전자빼고/3서식지빼고
HANDLE=None
FRAME_FIXATION=3
