import os


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STIMULI_DIR = os.path.join(BASE_DIR, "stimuli")


DURATION=2.0
WAITING=0

TARGET_REFRESH_HZ = 144
REFRESH_RATE_TOLERANCE_HZ = 1.0


def seconds_to_frames(duration_s):
    return int(round(duration_s * TARGET_REFRESH_HZ))


PREMISE_DURATION_S = 3.0
RESPONSE_TIMEOUT_S = 10.0
FEEDBACK_DURATION_S = 0.5
ISI_MIN_S = 0.75
ISI_MAX_S = 1.0
PRACTICE_FEEDBACK_DURATION_S = 0.5
PRACTICE_DONE_DURATION_S = 2.5
PRACTICE_PHASE_GAP_DURATION_S = 0.5

PREMISE_FRAMES = seconds_to_frames(PREMISE_DURATION_S)
RESPONSE_TIMEOUT_FRAMES = seconds_to_frames(RESPONSE_TIMEOUT_S)
FEEDBACK_FRAMES = seconds_to_frames(FEEDBACK_DURATION_S)
PRACTICE_FEEDBACK_FRAMES = seconds_to_frames(PRACTICE_FEEDBACK_DURATION_S)
PRACTICE_DONE_FRAMES = seconds_to_frames(PRACTICE_DONE_DURATION_S)
PRACTICE_PHASE_GAP_FRAMES = seconds_to_frames(PRACTICE_PHASE_GAP_DURATION_S)

WIDTH = 1920
HEIGHT = 1080
FRAME_EXAMPLE_fa = 4
FRAME_EXAMPLE_ga = 5
FRAME_EXAMPLE_fr = 6
FRAME_EXAMPLE_gr = 7
FRAME_EXAMPLE_ha = 8
FRAME_EXAMPLE_hr = 9
FRAME_EXAMPLE_fcs = 10
FRAME_EXAMPLE_fcf = 11
FRAME_EXAMPLE_gcs = 12
FRAME_EXAMPLE_gcf = 13
FRAME_EXAMPLE_hcs = 14
FRAME_EXAMPLE_hcf = 15
FRAME_EXAMPLE_bs = 16
FRAME_EXAMPLE_bss = 17
FRAME_EXAMPLE_bf = 18
waiting_frames=PREMISE_FRAMES
MODE=1
#0전부/1food빼고/2유전자빼고/3서식지빼고
HANDLE=None
FRAME_FIXATION=3
